### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by maxkwallace** [IvyApp/ivy-tabs#10]
I think those of us using this addon are currently pointing our `package.json`s at the `master` branch or a specific commit. I ran into issues before when simply using the latest release, which was cut back in May 2015, and is missing several commits in `master`.

It would be great if someone could make a new release of this addon! Happy to help out if there's anything I can do.

**Comment by omghax** [comment]
Previously, the README suggested installing from GitHub. I've updated it to use the more idiomatic `ember install ivy-tabs` now, and published a new 1.2.0 release which fixes some problems when using it with the latest versions of Ember (1.13 and up). Give it a try and let me know if you run into any problems with it.
