### ISSUE TITLE
Uncaught Error: Assertion Failed: A helper named 'tabs.tablist' could not be found

### ISSUE THREAD

**Issue by ngelx** [IvyApp/ivy-tabs#16]
Hey there,
I've installed the plugin an copy/paste the example code, but i'm getting this issue on ember debug console.

`ember.debug.js:16628 Uncaught Error: Assertion Failed: A helper named 'tabs.tablist' could not be found`

Any idea what is going on? 
Thanks,

```
$ember -v
ember-cli: 2.4.3
node: 5.10.0
...
"ivy-tabs": "1.2.0"
```

**Comment by omghax** [comment]
I'm guessing you read the README from the `master` branch, which is for the (currently unreleased) 2.0 version. The version you're using, 1.2.0, doesn't support contextual components, so the usage is slightly different. You can find the README for 1.2.0 [here](https://github.com/IvyApp/ivy-tabs/blob/v1.2.0/README.md). Hope that helps, and sorry for the confusion :)
