### ISSUE TITLE
Short circuit non-displayed tabs using if blocks?

### ISSUE THREAD

**Issue by Kilowhisky** [IvyApp/ivy-tabs#17]
In ember if you wrap template code in an if block ember won't evaluate anything inside the block. This includes any interior computed properties.

Would it be possible to internally wrap the {{yield}} for the tab-panels in an {{#if}} block? This will help to speed up initial renders with the tab panel as it no longer has to render all the tabs at once.  I've been doing this with some instances where i use the tab panel and its worked out quite well. Its just really hard to implement on a large scale across the app.

**Comment by morschtk** [comment]
What I did was created a ivy-tab-panel.hbs template with 
{{#if active}}
  {{yield}}
{{/if}}
So that way it only renders the currently active tab. 

I had to incorporate this fix because I was running into styling issues switching between tabs that had dynamic tables on each.

**Comment by nbibler** [comment]
As was mentioned in the pull request, there's a lot that would go into correctly rendering ARIA attributes for dynamically-inserted or -loaded content into tab panels.

If using the `if` blocks works for you and your environment, then continue to do that. You can always extend ivy-tabs within your application to have a new default template, as you've mentioned.
