### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by rwwagner90** [IvyApp/ivy-tabs#19]
I noticed that this relies on bootstrap for styling, but I wanted to do a Material UI theme, so I adapted some examples online and got the styles working. I assume styles are left out of the addon on purpose, but what would you recommend for providing themes to users? I would be glad to share my work.

**Comment by rwwagner90** [comment]
Are the maintainers of this addon active on here? Please respond if you can.

**Comment by rwwagner90** [comment]
@omghax @nbibler ^

**Comment by nbibler** [comment]
Hmm... there shouldn't be any hard dependency on using Bootstrap for the addon functionality, that is correct. I think Bootstrap was only added to make the test application look alright when demo'ing it via http://ivyapp.github.io/ivy-tabs/.

As for sharing themes: it's hard to say, really. Every app is different and uses different CSS frameworks, design standards, etc. I think that's mainly the reason why this addon is generic. So, to have an "official theme pool" or something seems a bit weird. Having a Wiki or blog posts that describe how to apply various frameworks sounds reasonable, however.

I'm curious to see what you had to do to make it work with Material; mostly to see if it was overly cumbersome to get it to work with Material.

**Comment by rwwagner90** [comment]
Hi @nbibler. I agree that there should be no theme imposed on anyone, but since all the classes and such already lend themselves to being able to drop in bootstrap and be styled, I think being able to drop in some material styles would be nice too. Could be a separate addon like `ivy-tabs-material-theme` and users could install it separately, and you could just link to it in the readme here. I'm at work now, and don't have the styles in front of me, but let me know your thoughts on my proposal.

**Comment by nbibler** [comment]
With the merge of #23, I think this should generally be addressed. Styling is now entirely up to the application.

**Comment by rwwagner90** [comment]
@nbibler while this is a good step, I still think it would make sense to share some common styles in another repo somewhere and link to them in the README or something, but definitely not a huge deal either way.
