### ISSUE TITLE
suggestions for mapping tabs to routes

### ISSUE THREAD

**Issue by jamesdixon** [IvyApp/ivy-tabs#20]
Hi, great work on this component!

Wanted to see if you had any suggestions for being able to map each tab to specific route?

**Comment by nbibler** [comment]
Can you describe a bit more what you mean by mapping each tab to a route? My first thought is that clicking an element on a page to transition to a new Route is `link-to` and not tabbing, at all. But, I think I'm just missing something. 😄 

Is the intent to be able to generate external links which activate a particular tab (a la jQuery UI's tabs with panel element ID as a link target)? What is the problem or goal you have in mind?

**Comment by jamesdixon** [comment]
@nbibler thanks for the quick response. Yes, the goal is to be able to externally link to a route and activate a specific tab.

**Comment by jamesdixon** [comment]
@nbibler I looked back on your comment about `link-to` and it finally hit me that it was indeed the simplest solution. Sometimes I overthink things 😄
