### ISSUE TITLE
Best way to handle case where no tabs are selected initially?

### ISSUE THREAD

**Issue by stickbyatlas** [IvyApp/ivy-tabs#26]
Hi folks,

Since we've implemented this addon it's been rapidly embraced throughout the mobile app we're working on. Thanks for making its implementation so simple and straightforward.

There's one use case that I can't figure out how to tackle: we have a few situations where the user will be presented a list of N tabs to choose from, all of which are inactive by default. Below the tabs, where the tab content will load, we intend to display a prompt to the user instructing them to select a tab above.

What's the best way to do this? The hackiest approach I can think of is to create N+1 tabs, and set `selectedIndex` to N+1 initially, like so:
```
{{#ivy-tabs on-select=(action (mut selectedIndex)) selected-index=selectedIndex as |tabs|}}

{{#tabs.tablist as |tablist|}}
  {{#tablist.tab}}Tab 1{{/tablist.tab}}
  {{#tablist.tab}}Tab 2{{/tablist.tab}}
  {{#tablist.tab}}Tab 3{{/tablist.tab}}
  {{#tablist.tab}}Can't see me{{/tablist.tab}}
{{/tabs.tablist}}

{{#tabs.tabpanel}}Tab 1 content{{/tabs.tabpanel}}		
{{#tabs.tabpanel}}Tab 2 content{{/tabs.tabpanel}}		
{{#tabs.tabpanel}}Tab 3 content{{/tabs.tabpanel}}		
{{#tabs.tabpanel}}Default prompt the user sees{{/tabs.tabpanel}}		

{{/ivy-tabs}}
```

Then, we'd explicitly hide the final `{{#tablist.tab}}` block so the user could never see or select it once they select a different tab.

I know this will work, but it feels icky. Is there a better approach? _Should_ this case be addressed by the addon, or is it out of scope?

Thanks again.

**Comment by nbibler** [comment]
So, there's a few pieces to this. First, index-based tab organization was dropped in the 3.0.0 release. Tabs and their panels are now selected and activated based on a unique `model` which you provide (it could be a number, a string, an Object, an Ember Data model, etc.).

As for having no default selection in the tabs, that's not provided directly by this library, although it's pretty easy to add. In one of my applications (using ivy-tabs 3.0), I basically did the following to extend `iyv-tabs-tablist` to short circuit the initial tab selection:

```javascript
import IvyTabsTablistComponent from 'ivy-tabs/components/ivy-tabs-tablist';
import { isNone } from 'ember-utils';

export default IvyTabsTablistComponent.extend({
  allowEmpty: false,

  selectTab() {
    if (isNone(this.get('selection')) && this.get('allowEmpty')) {
      return;
    }

    this._super(...arguments);
  }
});
```

Then, in my template, I just `{{#tabs.tablist allowEmpty=true as |tablist|}}` to identify when I want a tab list to not default-select.

**Comment by nbibler** [comment]
With no response, I presume this issue is closed. Reopen if you have further problems.
