### ISSUE TITLE
Tabs disappears when windows is to small to display all of them

### ISSUE THREAD

**Issue by olivierchatry** [IvyApp/ivy-tabs#30]
Hello !

First thanks for this project, it is really nice.

I was wondering if there is anyway to have scroll arrow ( or something equivalent ) when there is to much tabs and they cannot be all displayed ?

**Comment by nbibler** [comment]
I'm not sure I understand the issue here.

The way this is worded, it sounds as though it is a presentation concern about how your application looks and behaves on various device window sizes. If that's the case, this is an issue with your application's styles than this library's functionality.

Am I misunderstanding your problem?

**Comment by olivierchatry** [comment]
I guess you can consider it like this, my problems is that when you have
too many tabs,  there is no way to have a 'scroll' arrow that let you
scroll through the tabs ( not a normal scroll bar but something nicer. ).
To do involve doing some stuff with the components itself and no styling
can hell.

**Comment by nbibler** [comment]
I think I understand what you're saying, but again, it sounds like a styling and presentation concern for your application. ivy-tabs does not define any styling or styles and leaves that up to your application. If you'd like to embed your tabs within a scrollable container with overflow and navigational components, that's fine - but that's your application concern, not the tab library's.

Maybe said differently: ivy-tabs does not dictate that you must present tabs as a horizontal "tab"/"folder" list. In some applications, we use it as a sidebar. So, it's entirely up to you and your application to present the tabs in a way that works for your use case. The library is and should be agnostic to that.

**Comment by olivierchatry** [comment]
Ok
