### ISSUE TITLE
Ember 2.10 compatibility

### ISSUE THREAD

**Issue by vluoto** [IvyApp/ivy-tabs#31]
It looks like the order in which components get destroyed has changed, which now causes unwanted behavior in your addon. Previously (in at least Ember 2.9 and supposedly many earlier versions) components would get destroyed from highest index to lowest index, yielding the wanted result of the previously selected tab being left in selected state. Now however they're getting destroyed the other way around, causing [selectNextTab](https://github.com/IvyApp/ivy-tabs/blob/master/addon/components/ivy-tabs-tablist.js#L195) to be called when other tabs still exist, which in turn will end up "incerementing selection by one" as in selecting the next tab as long as there is a next tab. Tested on 3.0.2.

**Comment by vluoto** [comment]
Looks like it used to – somewhat unsurprisingly – work the other way around before. As in the selection would get decremented by one whenever the tabs would get unregistered on destroy. Worth noting that the scenario I'm describing here assumes the `selection` used is defined on a Controller.

So now I'm wondering what the correct approach to avoiding this unwanted behavior would be. I do understand the reasoning behind changing selected tab when the currently selected tab gets unregistered, but unfortunately that isn't always the preferred behavior. I suppose one approach would be to use a Component to encapsulate the tabs to work around long lived variables on singleton Controllers. Thoughts?

**Comment by omghax** [comment]
I'm not sure I understand. Here's the "Dynamic Tabs" example page running under Ember 2.10:

![dec-01-2016 11-39-45](https://cloud.githubusercontent.com/assets/1123/20803635/e22cce74-b7bd-11e6-93ba-7d889f46353e.gif)

This uses a `selection` property defined on the controller, which I've also added to the template in this example to show its value changing. It looks like the behavior is the same on the [GitHub pages](https://ivyapp.github.io/ivy-tabs/) demo app, which is still using Ember 2.9.

**Comment by vluoto** [comment]
Yeah so in the demo app you can try the following out to see what I mean:

1. click 'Tab C'
2. click 'Query Parameters Example'
3. click 'Basic Example'
4. tab selection has now changed to 'Tab B'
5. click 'Query Parameters Example'
6. click 'Basic Example'
7. tab selection has now changed to 'Tab A'

**Comment by omghax** [comment]
Oh, I see now. Thanks for the repro steps. Linking this with #32 since that's where the Ember upgrade is happening.

**Comment by omghax** [comment]
@vluoto this should be fixed in the `ember-cli-2.10` branch...do you mind giving it a try in your app and making sure everything's good?

**Comment by vluoto** [comment]
Works like a charm 🙌🏻

**Comment by omghax** [comment]
Good to hear, thanks! I've released 3.1.0, which includes these fixes.
