### ISSUE TITLE
Addon templates were detected, but there are no template compilers registered

### ISSUE THREAD

**Issue by jeregrine** [IvyApp/ivy-tabs#35]
When installing and running your plugin I get the following.
```
Addon templates were detected, but there are no template compilers registered for `ivy-tabs`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ivy-tabs`'s `package.json`.
```

**Comment by nbibler** [comment]
From what I can tell, `ember-cli-htmlbars` has been a `dependency` (not a `devDependency`) since March 24, 2016 (as of 23d850d).

Is this still a problem for you?

If so, what is your environment? Ember version, Ember CLI version, Node version, etc...

**Comment by nbibler** [comment]
No response. Closing issue.
