### ISSUE TITLE
how to select a default tab 

### ISSUE THREAD

**Issue by thilinadinith** [IvyApp/ivy-tabs#43]
i would like to know how to select a default tab when there is several tabs
let say i have tabA, tabB, tabC and i want to display tabB in initial load

**Comment by nbibler** [comment]
You can just pass a `selection` value to the `ivy-tabs` container, which should match the desired tab's model value. You could look at the example app where it's done for the query string selector:

https://ivyapp.github.io/ivy-tabs/#/query-params?tab=C

https://github.com/IvyApp/ivy-tabs/blob/c91aadbe238fb923cee0a873a9d9baaf74afb5b8/tests/dummy/app/controllers/query-params.js#L4

https://github.com/IvyApp/ivy-tabs/blob/c91aadbe238fb923cee0a873a9d9baaf74afb5b8/tests/dummy/app/templates/query-params.hbs#L6
