### ISSUE TITLE
Missing ivy-tab index property when used inside a conditional

### ISSUE THREAD

**Issue by omghax** [IvyApp/ivy-tabs#5]
For some reason, rendering an `ivy-tab` component inside a conditional will cause the `index` property to not be set correctly.

For example:

```handlebars
{{#ivy-tabs-list}}
  {{#if trueThing}}
    {{ivy-tab}}
  {{/if}}
{{/ivy-tabs-list}}
```

This only seems to happen if the conditional is a property. Using `{{#if true}}` will not cause the bug.

**Comment by omghax** [comment]
I suspect that this is no longer an issue now that we've switched away from using `parentView`, but I'll need to double-check.

**Comment by nbibler** [comment]
With #21, index is no longer used within the addon.
