### ISSUE TITLE
active class not set

### ISSUE THREAD

**Issue by mohlek** [IvyApp/ivy-tabs#9]
In ember 2.2.0 it seems that classNameBindings: ['active'] isn't triggering correctly.

https://github.com/emberjs/ember.js/issues/12814

Any idea?

**Comment by mohlek** [comment]
Got it. It was an addon. Liquid-Fire .. As always ^^

I didn't defined any transitions and that seems to break something. I don't know what.
After defining transitions everything works fine.

**Comment by constantm** [comment]
Just ran into this issue was well. However, I'm not using Liquid-Fire.
